---
swagger: "2.0"
info:
  description: "Simple REST API service."
  version: "1.0.0"
  title: "Service 4"
  contact:
    email: "tisnik@somewhere.else"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api/v1"
tags:
- name: "Basic operations"
  description: "Basic operations"
- name: "Service settings"
  description: "The service settings"
schemes:
- "https"
- "http"
paths:
  /liveness:
    get:
      tags: [Service settings]
      operationId: "service4.get_liveness"
      summary: "Get service liveness"
      responses:
        200:
          description: Service is alive
  /readiness:
    get:
      tags: [Service settings]
      operationId: "service4.get_readiness"
      summary: "Get service readiness"
      responses:
        200:
          description: Service is ready
  /message_statistic:
    get:
      tags: [Basic operations]
      operationId: "service4.message_statistic"
      summary: "Returns basic statistic about sent messages"
      responses:
        200:
          description: Query was successful
      produces:
      - "application/json"
  /message/{recipient}:
    post:
      tags: [Basic operations]
      operationId: "service4.send_message"
      summary: "Post a message"
      consumes:
      - "text/plain"
      produces:
      - "application/json"
      parameters:
      - name: "recipient"
        in: "path"
        description: "The recipient for the message"
        required: true
        type: "string"
      - name: "message"
        in: body
        description: "Message body"
        required: true
        schema:
          type: string
      responses:
        200:
          description: "Successful operation"
        400:
          description: "Invalid recipient supplied"
        404:
          description: "The specified recipient was not found"
        405:
          description: "Not allowed - it is not allowed to send the message to selected recipient"
        500:
          description: "Any other failure"
definitions: {}
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
